language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "8"
  - "6"
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
before_script: "npm run pretest"
script: "npm run-script coverage"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
